site_name: [regorxxx's Foobar2000 SMP Scripts](index.md)
copyright: Copyright &copy; 2022 regorxxx
theme:
  name: material
  icon:
    logo: material/home
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material//brightness-7
        name: "Switch to light mode"
    - scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: "Switch to dark mode"
markdown_extensions:
  - admonition
  - attr_list
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "#"
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/regorxxx
extra_css:
  - stylesheets/extra.css
nav:
  - [ALL]: index.md
  - Playlist Manager: scripts/playlist-manager-smp.md
  - Playlist Tools: scripts/playlist-tools-smp.md
  - Device Priority: scripts/device-priority-smp.md
  - ListenBrainz: scripts/listenbrainz-smp.md
  - World Map: scripts/world-map-smp.md
  - Search by Distance: scripts/search-by-distance-smp.md
  - Not a Waveform Seekbar: scripts/not-a-waveform-seekbar-smp.md
  - Last.fm: scripts/lastfm-smp.md
  - ajquery-xxx: others/ajquery-xxx.md